import { baseApi } from './baseApi';
import {
  datasetEndpoints,
  useListDatasetsQuery,
  useGetDatasetQuery,
  useUploadDatasetMutation,
  useSwitchDatasetSheetMutation,
  useDeleteDatasetMutation,
  useCopyDatasetMutation,
  usePreviewDatasetQuery,
  useCleanDatasetMutation,
  useAutoCleanMutation,
  useUpdateColumnTypeMutation,
  useGetDatasetVersionsQuery,
  useRestoreVersionMutation,
  useGetAnalysisHistoryQuery,
  useGetAuditTrailQuery,
  useGetTransformCatalogQuery,
  useGetTransformRecommendationsQuery,
  usePreviewTransformMutation,
  useApplyTransformsMutation,
  useComputeVariableMutation,
} from './endpoints/datasetEndpoints';
import {
  analysisEndpoints,
  useGetCapabilitiesQuery,
  useGetExcludedColumnsQuery,
  useSetExcludedColumnsMutation,
  useRunAnalysisMutation,
  useGetCorrelationsQuery,
  useRunTestMutation,
  useGetChartDataMutation,
  useRunPCAMutation,
  useRunCAMutation,
  useRunMCAMutation,
  useGetDiagnosticsQuery,
  useRunStationarityMutation,
} from './endpoints/analysisEndpoints';
import {
  modelingEndpoints,
  useTrainModelsMutation,
  useGetModelResultsQuery,
  useRunTimeSeriesMutation,
  useRunMultivariateTimeSeriesMutation,
  useGetFeatureRangesQuery,
  usePredictMutation,
  useRecommendTestsMutation,
  useCheckAssumptionsMutation,
  useRecommendModelsMutation,
  useCreateScenarioMutation,
  useCreatePresetScenariosMutation,
  useRunScenariosMutation,
  useListScenariosQuery,
  useGetSensitivityMutation,
  useGetTornadoMutation,
  useGetPartialDependenceMutation,
  useRunMonteCarloMutation,
  useRunStressTestMutation,
} from './endpoints/modelingEndpoints';
import {
  pipelineEndpoints,
  useGenerateReportMutation,
  useGenerateProfessionalReportMutation,
  useDetectPipelineQuery,
  useBuildPipelineRecipeMutation,
  useExecuteAutoPipelineMutation,
  useGenerateCanvasFromRecipeMutation,
  useExportCanvasCodeMutation,
  useGetInsightsQuery,
} from './endpoints/pipelineEndpoints';
import {
  platformEndpoints,
  useListJobsQuery,
  useSubmitJobMutation,
  useGetJobStatusQuery,
  useCancelJobMutation,
  useGenerateExtensionMutation,
  useSaveExtensionMutation,
  useListExtensionsQuery,
  useListExtensionTemplatesQuery,
  useRunExtensionMutation,
  useRunExtensionCodeMutation,
  useListMarketplaceItemsQuery,
  useGetMarketplaceItemQuery,
  useExportMarketplaceItemQuery,
  useImportMarketplaceItemMutation,
} from './endpoints/platformEndpoints';

export {
  baseApi as api,
  datasetEndpoints,
  analysisEndpoints,
  modelingEndpoints,
  pipelineEndpoints,
  platformEndpoints,
};

export type { PaginatedDatasets, PaginatedJobs, StationarityResult } from './baseApi';

export {
  useListDatasetsQuery,
  useGetDatasetQuery,
  useUploadDatasetMutation,
  useSwitchDatasetSheetMutation,
  useDeleteDatasetMutation,
  useCopyDatasetMutation,
  usePreviewDatasetQuery,
  useCleanDatasetMutation,
  useAutoCleanMutation,
  useGetCapabilitiesQuery,
  useGetExcludedColumnsQuery,
  useSetExcludedColumnsMutation,
  useRunAnalysisMutation,
  useGetCorrelationsQuery,
  useRunTestMutation,
  useTrainModelsMutation,
  useGetModelResultsQuery,
  useGenerateReportMutation,
  useGenerateProfessionalReportMutation,
  useRunTimeSeriesMutation,
  useRunMultivariateTimeSeriesMutation,
  useGetChartDataMutation,
  useGetTransformCatalogQuery,
  useGetTransformRecommendationsQuery,
  usePreviewTransformMutation,
  useApplyTransformsMutation,
  useComputeVariableMutation,
  useRunPCAMutation,
  useRunCAMutation,
  useRunMCAMutation,
  useGetFeatureRangesQuery,
  usePredictMutation,
  useUpdateColumnTypeMutation,
  useGetDatasetVersionsQuery,
  useRestoreVersionMutation,
  useGetAnalysisHistoryQuery,
  useGetAuditTrailQuery,
  useGetDiagnosticsQuery,
  useGetInsightsQuery,
  useDetectPipelineQuery,
  useBuildPipelineRecipeMutation,
  useExecuteAutoPipelineMutation,
  useGenerateCanvasFromRecipeMutation,
  useExportCanvasCodeMutation,
  useRecommendTestsMutation,
  useCheckAssumptionsMutation,
  useRecommendModelsMutation,
  useListJobsQuery,
  useSubmitJobMutation,
  useGetJobStatusQuery,
  useCancelJobMutation,
  useCreateScenarioMutation,
  useCreatePresetScenariosMutation,
  useRunScenariosMutation,
  useListScenariosQuery,
  useGetSensitivityMutation,
  useGetTornadoMutation,
  useGetPartialDependenceMutation,
  useRunMonteCarloMutation,
  useRunStressTestMutation,
  useRunStationarityMutation,
  useGenerateExtensionMutation,
  useSaveExtensionMutation,
  useListExtensionsQuery,
  useListExtensionTemplatesQuery,
  useRunExtensionMutation,
  useRunExtensionCodeMutation,
  useListMarketplaceItemsQuery,
  useGetMarketplaceItemQuery,
  useExportMarketplaceItemQuery,
  useImportMarketplaceItemMutation,
};
